### ISSUE TITLE
Dati duplicati

### ISSUE THREAD

**Issue by francescozaia** [italia/docs-italia-starter-kit#10]
Non sono convinto sull'opportunità di [avere il campo `name`](https://github.com/italia/docs-italia-starter-kit/blob/master/repo-configurazione/projects_settings.yml#L23) all'interno dei documenti listati dentro `projects_settings.yml`, in quanto **già presente** nei singoli `document_settings.yml`.

Se questa scelta era stata fatta per avere già il `nome` disponibile ad un livello più alto, purtroppo possiamo già affermare che tale soluzione non sarà sufficiente, in quanto nella SERP è presente sia il nome che la descrizione dei singoli documenti:

<img width="928" alt="schermata 2018-07-05 alle 15 26 08" src="https://user-images.githubusercontent.com/481084/42325938-f160eeba-8067-11e8-9f61-beef1ba15ca5.png">

Per questo, avrei due proposte:

### - 1
Lasciare soltanto la lista dei repo (proposta che caldeggio molto):
```
documents:
  - project-document-doc
  - another-project-document-doc
```

### - 2
Includere anche un campo `description` nei documenti listati:
```
documents:
  - name: Documento del progetto
    description: Descrizione del documento del progetto
    repository: project-document-doc
  ...
```

Quando riuscite, mi piacerebbe avere un feedback in particolare da @pdavide e da @xrmx anche per eventuali limiti o impatto nella gestione dell'indicizzazione.
